#!/usr/bin/env bash
# update man docs...
#cp ../../docs/man/tttt.md tttt.1.md
# fetch latest tttt
#cp ../../tttt.py tttt
# update package changelog
#dch -i
pandoc tttt.1.md -s -t man > tttt.1
# update package control
# vi debian/control
# for building deb package for local use..
debuild --no-tgz-check -uc -us
# for building source package for PPA
#debuild -S 
debuild -T clean
# go update package install script
# vi ../install.sh
