name: Deploy web_tea to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger when pushing to master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push to gh-pages

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload web_tea directory
        uses: actions/upload-pages-artifact@v2
        with:
          path: html/web_tea  # This is your deployable folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
